#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "{{username}}"
email = "{{email}}"

[aliases]
lgdiv = [
  "log",
  "-r",
  'fork_point($1 | $1@origin)::($1 | $1@origin)',
]
'slice(from)' = 'ancestors(reachable(from, mutable()), 2)'
'slice' = 'slice(@)'
