#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "{{username}}"
email = "{{email}}"

[ui]
default-command = "log"

[colors]
"bookmarks" = { fg = "black", bg = "magenta", bold = true }
"working_copy bookmarks" = { fg = "black", bg = "bright magenta" }
"mine author name" = { fg = "green" }

[revset-aliases]
'closest_bookmark(to)' = 'latest(::to & bookmarks())'
'closest_pushable(to)' = 'latest(::to & ~description(exact:"") & (~empty() | merges()))'
'prevb()' = 'closest_bookmark(closest_bookmark(@)-)'

[aliases]
difft = ["diff", "--tool", "difft"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]
lgdiv = ["util", "exec", "--", "zsh", "-c", """
    local input="${1:-$( \
        jj log --no-graph -n1 -r 'closest_bookmark(@)' \
        -T 'bookmarks.map(|b| b.name()).join(" ")' --color=never \
    )}"
    local bookmarks=(${(z)input})
    local bmk=$bookmarks[1]

    [[ -z $bmk ]] && { echo "No bookmark found"; return 1 }

    jj log -r "fork_point($bmk | $bmk@origin)::($bmk | $bmk@origin)"
""", ""]

[template-aliases]
'format_short_signature(signature)' = '''
label(
  if(signature.email() == config("user.email").as_string(), "mine", ""),
  coalesce(signature.name(), signature.email(), email_placeholder)
)
'''
'format_timestamp(timestamp)' = '''
if(timestamp.before("this january"),
  timestamp.format("%Y-%m-%d %H:%M"),
  timestamp.format("%d %b %H:%M")
)
'''

[[--scope]]
--when.environments = ["JJUI"]
[--scope.ui]
diff-formatter = "delta"
