export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BIN_HOME="$HOME/.local/bin"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export GHCUP_USE_XDG_DIRS=true
# Virtualenv
export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"
export PROJECT_HOME="$HOME/devel"

export LC_CTYPE="en_US.UTF-8"
export LESS="iMRj5"
export BROWSER="{{browser}}"
export EDITOR="nvim"
export TERMINAL="{{terminal}}"

export _JAVA_OPTIONS="$_JAVA_OPTIONS -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"

typeset -U PATH path
path=($XDG_BIN_HOME $path)

# Rancher docker shims
[[ -d $HOME/.rd/bin ]] && path=($HOME/.rd/bin $path)
