[helpers]


[linux]
depends = ["nvim", "sway", "niri", "shell", "dev", "apps"]

[linux.files]
"shell/paru.conf" = "$XDG_CONFIG_HOME/paru/paru.conf"
"fonts.conf"      = "$XDG_CONFIG_HOME/fontconfig/fonts.conf"
"bin/synckdbx"    = "$XDG_BIN_HOME/synckdbx"


[programs.variables]
terminal = "kitty"
browser  = "firefox-developer-edition"


[colors.variables.colors]
# tokyonight
background = "1a1b26"
bg_light   = "3b4261"
foreground = "c0caf5"
cursor     = "c0caf5"
accent     = "7aa2f7"
highlight  = "313739"
# 16-bit colors
black      = "15161E"
red        = "f7768e"
green      = "9ece6a"
orange     = "e0af68"
yellow     = "e0af68"
blue       = "7aa2f7"
purple     = "bb9af7"
cyan       = "7dcfff"
white      = "a9b1d6"
gray       = "414868"


[nvim.files]
nvim = "$XDG_CONFIG_HOME/nvim"


[shell]
depends = ["programs"]

[shell.files]
"shell/zsh/zshenv"      = "$HOME/.zshenv"
"shell/zsh/zshrc"       = "$XDG_CONFIG_HOME/zsh/.zshrc"
"shell/zsh/p10k.zsh"    = "$XDG_CONFIG_HOME/zsh/p10k.zsh"
"shell/zsh/completions" = "$XDG_CONFIG_HOME/zsh/completions"
"shell/tmux.conf"       = "$XDG_CONFIG_HOME/tmux/tmux.conf"
"shell/gitconfig"       = "$XDG_CONFIG_HOME/git/config"
"shell/tigconfig"       = "$XDG_CONFIG_HOME/tig/config"
"shell/gitui"           = "$XDG_CONFIG_HOME/gitui"


[waybar]
depends = ["colors"]

[waybar.files]
"sway/waybar"                = "$XDG_CONFIG_HOME/waybar"
"bin/waybar_mpris"           = { target = "$XDG_BIN_HOME/waybar_mpris", type = "symbolic" }
"bin/waybar_keyboard_layout" = "$XDG_BIN_HOME/waybar_keyboard_layout"


[sway]
depends = ["colors", "programs", "waybar"]

[sway.files]
"sway/sway"                   = "$XDG_CONFIG_HOME/sway"
"sway/swaylock"               = "$XDG_CONFIG_HOME/swaylock/config"
"sway/gammastep.ini"          = "$XDG_CONFIG_HOME/gammastep/config.ini"
"sway/wofi"                   = "$XDG_CONFIG_HOME/wofi"
"sway/mako"                   = "$XDG_CONFIG_HOME/mako/config"
"sway/kanshi"                 = "$XDG_CONFIG_HOME/kanshi/config"
"sway/libinput-gestures.conf" = "$XDG_CONFIG_HOME/libinput-gestures.conf"
"bin/swayrun"                 = "$XDG_BIN_HOME/swayrun"
"bin/grimshot"                = "$XDG_BIN_HOME/grimshot"
"bin/swayextmsg"              = "$XDG_BIN_HOME/swayextmsg"

[sway.variables]
device = "unknown"


[niri]
depends = ["colors", "waybar"]

[niri.files]
"niri/"               = "$XDG_CONFIG_HOME/niri/"
"bin/nirirun"         = "$XDG_BIN_HOME/nirirun"
"bin/niri_scratchpad" = "$XDG_BIN_HOME/niri_scratchpad"


[dev]
depends = ["colors"]

[dev.files]
"apps/alacritty.yml" = "$XDG_CONFIG_HOME/alacritty/alacritty.yml"
"apps/ideavimrc"     = "$HOME/.ideavimrc"
"apps/kitty.conf"    = "$XDG_CONFIG_HOME/kitty/kitty.conf"


[apps.files]
"apps/mpv.conf"      = "$XDG_CONFIG_HOME/mpv/mpv.conf"
"apps/zathurarc"     = "$XDG_CONFIG_HOME/zathura/zathurarc"
