[helpers]


[default]
depends = ["nvim", "sway", "shell", "apps"]


[programs.variables]
terminal = "kitty"
browser  = "firefox-developer-edition"

[colors.variables.colors]
# tokyonight
background = "1a1b26"
bg_light   = "3b4261"
foreground = "c0caf5"
cursor     = "c0caf5"
accent     = "7aa2f7"
accent_dark = "507bbe"
highlight  = "313739"
highlight_rgb = "49, 55, 57"
# 16-bit colors
black      = "15161E"
red        = "f7768e"
red_dark   = "db4b4b"
green      = "9ece6a"
orange     = "e0af68"
yellow     = "e0af68"
blue       = "7aa2f7"
blue_dark  = "394b70"
purple     = "bb9af7"
cyan       = "7dcfff"
white      = "a9b1d6"
gray       = "414868"

# gruvbox-material
# background = "1d2021"
# foreground = "d4be98"
# cursor     = "a89984"
# accent     = "a9b665"
# highlight  = "313739"
# # 16-bit colors
# black      = "665c54"
# red        = "ea6962"
# green      = "a9b665"
# orange     = "e78a4e"
# yellow     = "d8a657"
# blue       = "7daea3"
# purple     = "d3869b"
# cyan       = "89b482"
# white      = "d4be98" -- original
# white      = "ffffff"
# gray       = "928374"

[nvim.files]
nvim = "$XDG_CONFIG_HOME/nvim"


[shell]
depends = ["programs"]

[shell.files]
"shell/zsh/zshenv"      = "$HOME/.zshenv"
"shell/zsh/zshrc"       = "$XDG_CONFIG_HOME/zsh/.zshrc"
"shell/zsh/p10k.zsh"    = "$XDG_CONFIG_HOME/zsh/p10k.zsh"
"shell/zsh/completions" = "$XDG_CONFIG_HOME/zsh/completions"
"shell/gitconfig"       = "$XDG_CONFIG_HOME/git/config"
"shell/tigconfig"       = "$XDG_CONFIG_HOME/tig/config"
"shell/gitui"           = "$XDG_CONFIG_HOME/gitui"
"shell/paru.conf"       = "$XDG_CONFIG_HOME/paru/paru.conf"


[sway]
depends = ["colors"]

[sway.files]
"sway/sway"                   = "$XDG_CONFIG_HOME/sway"
"sway/waybar"                 = "$XDG_CONFIG_HOME/waybar"
"sway/swaylock"               = "$XDG_CONFIG_HOME/swaylock/config"
"sway/gammastep.ini"          = "$XDG_CONFIG_HOME/gammastep/config.ini"
"sway/wofi"                   = "$XDG_CONFIG_HOME/wofi"
"sway/mako"                   = "$XDG_CONFIG_HOME/mako/config"
"sway/kanshi"                 = "$XDG_CONFIG_HOME/kanshi/config"
"sway/libinput-gestures.conf" = "$XDG_CONFIG_HOME/libinput-gestures.conf"
"bin/swayrun"                 = "$XDG_BIN_HOME/swayrun"
"bin/grimshot"                = "$XDG_BIN_HOME/grimshot"
"bin/waybar_mpris"            = { target = "$XDG_BIN_HOME/waybar_mpris", type = "symbolic" }
"bin/waybar_keyboard_layout"  = "$XDG_BIN_HOME/waybar_keyboard_layout"
"bin/swayextmsg"              = "$XDG_BIN_HOME/swayextmsg"

[sway.variables]
device = "unknown"


[apps.files]
"apps/alacritty.yml" = "$XDG_CONFIG_HOME/alacritty/alacritty.yml"
"apps/ideavimrc"     = "$HOME/.ideavimrc"
"apps/kitty.conf"    = "$XDG_CONFIG_HOME/kitty/kitty.conf"
"apps/mpv.conf"      = "$XDG_CONFIG_HOME/mpv/mpv.conf"
"apps/zathurarc"     = "$XDG_CONFIG_HOME/zathura/zathurarc"
"fonts.conf"         = "$XDG_CONFIG_HOME/fontconfig/fonts.conf"
"bin/synckdbx"       = "$XDG_BIN_HOME/synckdbx"
